### ISSUE TITLE
Use $HOME/.config for config file location

### ISSUE THREAD

**Issue by brlin-tw** [om26er/surc#6]
The access can be granted by leveraging [the `personal-files` interface](https://forum.snapcraft.io/t/the-personal-files-interface/9357).

**Comment by om26er** [comment]
So, do I need to ask for that interface to auto-connect in the forums first and once its approved then merge your change (uncommented) ?

**Comment by brlin-tw** [comment]
Yes.

**Comment by om26er** [comment]
Closing that now since we decided in keeping config inside $SNAP_USER_DATA
